
version: "3.1"
services:
  fend:
    build: fend/
    container_name: fend
    # volumes:
    #   - "./fend:/app"
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - server

  server:
    build: server/
    container_name: server
    # volumes:
    #   - "./server:/app"
    ports:
      - "3001:3001"
    networks:
      - app-network
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/docker_inputs_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    user: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=docker"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - docker_inputs_db:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  docker_inputs_db: